-- MySQL Script generated by MySQL Workbench
-- Tue Feb 13 15:32:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema videolib
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `videolib` ;

-- -----------------------------------------------------
-- Schema videolib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `videolib` DEFAULT CHARACTER SET utf8 ;
USE `videolib` ;

-- -----------------------------------------------------
-- Table `videolib`.`action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`action` ;

CREATE TABLE IF NOT EXISTS `videolib`.`action` (
  `Type` VARCHAR(45) NOT NULL DEFAULT 'image',
  `Action` VARCHAR(255) NULL DEFAULT NULL,
  `Parameter` VARCHAR(45) NULL DEFAULT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `EventId` INT(10) UNSIGNED NOT NULL,
  `ResourceSeq` INT(10) UNSIGNED NOT NULL,
  `Checked` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`EventId`, `ResourceSeq`, `Color`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videolib`.`ad_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`ad_events` ;

CREATE TABLE IF NOT EXISTS `videolib`.`ad_events` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `PlayoutMethod` VARCHAR(30) NULL DEFAULT NULL,
  `PlayoutTimeSpan` INT(10) UNSIGNED NULL DEFAULT NULL,
  `PlayoutSequence` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videolib`.`ad_events_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`ad_events_schedule` ;

CREATE TABLE IF NOT EXISTS `videolib`.`ad_events_schedule` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `EventId` INT(10) UNSIGNED NOT NULL,
  `ScheduleDate` DATETIME(2) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `ScheduleDate_INDEX` (`ScheduleDate` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `videolib`.`ad_location_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`ad_location_tags` ;

CREATE TABLE IF NOT EXISTS `videolib`.`ad_location_tags` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videolib`.`ad_resources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`ad_resources` ;

CREATE TABLE IF NOT EXISTS `videolib`.`ad_resources` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Path` VARCHAR(255) NOT NULL,
  `ThumbnailPath` VARCHAR(255) NOT NULL,
  `CreateTime` DATETIME(2) NOT NULL,
  `MediaType` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `CreateTime` (`CreateTime` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 92
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videolib`.`event_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`event_location` ;

CREATE TABLE IF NOT EXISTS `videolib`.`event_location` (
  `EventId` INT(10) NOT NULL,
  `LocationId` INT(10) NOT NULL,
  PRIMARY KEY (`EventId`, `LocationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videolib`.`event_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`event_resource` ;

CREATE TABLE IF NOT EXISTS `videolib`.`event_resource` (
  `EventId` INT(10) UNSIGNED NOT NULL,
  `ResourceId` INT(10) UNSIGNED NOT NULL,
  `ResourceSeq` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `ResourcePlayWeight` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`EventId`, `ResourceSeq`),
  INDEX `ResourceId` (`ResourceId` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videolib`.`event_so`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`event_so` ;

CREATE TABLE IF NOT EXISTS `videolib`.`event_so` (
  `EventId` INT(10) UNSIGNED NOT NULL,
  `SoId` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`EventId`, `SoId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videolib`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`log` ;

CREATE TABLE IF NOT EXISTS `videolib`.`log` (
  `ActionTime` DATETIME(6) NOT NULL,
  `Action` VARCHAR(255) NOT NULL,
  `UserId` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ActionTime`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videolib`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`schedule` ;

CREATE TABLE IF NOT EXISTS `videolib`.`schedule` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ScheduleDate` DATE NULL DEFAULT NULL,
  `CreateDate` DATETIME(2) NULL DEFAULT NULL,
  `EventId` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ScheduleDateEnd` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `DateTime` (`ScheduleDate` ASC, `ScheduleDateEnd` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `videolib`.`so_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`so_settings` ;

CREATE TABLE IF NOT EXISTS `videolib`.`so_settings` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videolib`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videolib`.`user` ;

CREATE TABLE IF NOT EXISTS `videolib`.`user` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Enable` TINYINT(4) NOT NULL DEFAULT '1',
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `EnableResource` VARCHAR(5) NULL DEFAULT 'x',
  `EnablePublish` VARCHAR(5) NULL DEFAULT 'x',
  `EnableLocation` VARCHAR(5) NULL DEFAULT 'x',
  `EnableSo` VARCHAR(5) NULL DEFAULT 'x',
  `EnableEvent` VARCHAR(5) NULL DEFAULT 'x',
  `EnableAdmin` TINYINT(4) NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UserId_UNIQUE` (`UserName` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
